const efb_var ={text:{
    create:"Create",
    define:"Define",
    formName:"Form Name",
    numberSteps:"Number of steps",
    createDate:"Create Date",
    edit:"Edit",
    content:"Content",
    trackNo:"Track No.",
    formDate:"Form Date",
    by:"By",
    ip:"IP",
    guest:"Guest",
    info:"Info",
    response:"Response",
    date:"Date",
    videoDownloadLink:"Video Download Link",
    downloadViedo:"Download Viedo",
    youCantUseHTMLTagOrBlank:"You can not use HTML Tag or send blank message.",
    error:"Error,",
    reply:"Reply",
    messages:"Messages",
    close:"Close",
    pleaseWaiting:"Please Waiting",
    loading:"Loading",
    remove:"Remove!",
    areYouSureYouWantDeleteItem:"Are you sure want to delete this item?",
    no:"NO",
    yes:"Yes",
    numberOfSteps:"Number of steps",
    easyFormBuilder:"Easy Form Builder",
    titleOfStep:"Title of step",
    proVersion:"Pro Version",
    getProVersion:"Get Pro version",
    clickHereGetActivateCode:"Click here to get Activate Code.",
    email:"Email",
    trackingCode:"Tracking code",		
    save:"Save",
    waiting:"Waiting",
    saved:"Saved",
    error:"Error,",
    stepName:"Step Name",
    IconOfStep:"Icon of step",
    define:"Define",
    stepTitles:"Step Titles",
    elements:"Elements:",
    delete:"Delete",
    newOption:"New option",
    documents:"Documents",
    image:"Image",
    media:"Media",
    videoOrAudio:"(Video or Audio)",
    zip:"Zip",
    required:"Required",
    button:"button",
    text:"text",
    password:"Password",
    emailOrUsername:"Email or Username",
    number:"number",
    file:"file",
    date:"date",
    tel:"tel",
    textarea:"textarea",
    checkbox:"checkbox",
    radiobutton:"radiobutton",
    multiselect:"multiselect",
    url:"url",
    range:"range",
    color:"color",
    fileType:"File Type",
    label:"Label:*",
    class:"Class",
    id:"ID",
    tooltip:"Tooltip",
    formUpdated:"The Form Updated",
    goodJob:"Good Job",
    formUpdatedDone:"The form has been successfully updated",
    formIsBuild:"The form is successfully built",
    formCode:"Form Code",
    close:"Close",
    done:"Done",
    demo:"Demo",
    alert:"Alert!",
    pleaseFillInRequiredFields:"Please fill in all required fields.",
    availableInProversion:"This option is available in Pro version",
    preview:"Preview",
    somethingWentWrongPleaseRefresh:"Something went wrong, Please refresh and try again",
    formNotCreated:"The form has not been created!",
    atFirstCreateForm:"At first create a form and add elemants then try again",
    formNotBuilded:"The form has not been builded!",
    allowMultiselect:"Allow multi-select",
    DragAndDropUI:"Drag and drop UI",
    clickHereForActiveProVesrsion:"Click here for Active Pro vesrsion",
    someStepsNotDefinedCheck:"Some steps not defined, Please check:",
    ifYouNeedCreateMoreThan2Steps:"If you need create more than 2 Steps, activeate ",
    youCouldCreateMinOneAndMaxtwo:"You can create minmum 1 and maximum 2 Steps.",
    youCouldCreateMinOneAndMaxtwenty:"You Could create minmum 1 Step and maximum 20 Step",
    selectOpetionDisabled:"Select a option (Disabled in test view)",
    DragAndDropA:"Drag and drop a",
    orClickHere:" or click here",
    pleaseEnterTheTracking:"Please enter the tracking code",
    somethingWentWrongTryAgain:"Something went wrong, Please refresh and try again",			
    enterThePhone:"Please Enter the phone number",			
    pleaseMakeSureAllFields:"Please make sure all fields are filled in correctly.",
    enterTheEmail:"Please Enter the Email address",
    formNotFound:"Form is not found",
    errorV01:"Error Code:V01",
    password8Chars:"Password must be at least 8 characters",
    registered:"Registered",
    yourInformationRegistered:"Your information is successfully registered",		
    youNotPermissionUploadFile:"You do not have permission to upload this file:",
    pleaseUploadA:"Please upload a",
    trackingForm:"Tracking Form",
    trackingCodeIsNotValid:"Tracking Code is not valid.",
    checkedBoxIANotRobot:"Please Checked Box of I am Not robot",
    step:"step",
    contactusForm:"Contact-us Form",
    newForm:"New Form",
    registerForm:"Register Form",
    loginForm:"Login Form",
    login:"Login",
    thisInputLocked:"this input is locked",
    subscriptionForm:"Subscription Form",
    supportForm:"Support Form",
    createBlankMultistepsForm:"Create a blank multisteps form.",
    createContactusForm:"Create a Contact us form.",
    createRegistrationForm:"Create a user registration(Sign-up) form.",
    createLoginForm:"Create a user login (Sign-in) form.",
    createnewsletterForm:"Create a newsletter form",
    createSupportForm:"Create a support contact form.",
    availableSoon:"Available Soon",
    advancedCustomization:"Advanced customization",
    contactUs:"Contact us",
    support:"Support",
    subscribe:"Subscribe",
    survey:"Survey ",
    reservation:"Reservation ",
    createsurveyForm:"Create survey or poll or questionnaire forms ",
    createReservationyForm:"Create reservation or booking forms ",
    send:"Send",
    thisElemantAvailableRemoveable:"This elemant is available and removeable.",
    thisElemantWouldNotRemoveableLoginform:"This elemant would not removeable in Login or Register form.",
    firstName:"First name",
    lastName:"Last name",
    message:"Message",
    subject:"Subject",
    phone:"Phone",
    register:"Register",
    username:"Username",
    EasyFormBuilder: "Get Easy Form Builder",
    showTrackingCode:"Show tracking Code",
    allStep:"all step",
    alertEmail:"Alert Email",
    whenEasyFormBuilderRecivesNewMessage:"(When the Form recives a new message, It will send an notification email to below email)",
    please:"Please"
}}